# Generated by Django 4.1 on 2022-10-31 04:22

import atletica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletica',
            name='logo',
            field=models.ImageField(null=True, upload_to=atletica.models.upload_photo),
        ),
    ]
