# Generated by Django 4.1 on 2023-03-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campanha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campanha",
            name="status",
            field=models.IntegerField(
                choices=[(1, "ativo"), (0, "inativo")], default=1
            ),
        ),
    ]
